// giftData.js
// 雁书风物池 — 100件真实历史文物数据
// 供 cloudfunctions/yan 和 yan-timer 共用
// 稀有度：1普通 / 2精良 / 3稀有 / 4传说
// 权重：{ small, medium, large } 对应信使运力

var GIFT_POOL = [
  // ========== 笔墨纸砚（10件） ==========
  {
    id: 'g-brush',
    name: '湖笔',
    icon: '🖌️',
    imageUrl: 'mini-assets/gifts/icons/g-brush.png',
    photoUrl: 'mini-assets/gifts/photos/g-brush.jpg',
    rarity: 1,
    type: '笔墨纸砚',
    dynasty: 'yuan',
    dynastyName: '元代',
    desc: '宣笔之冠，锋颖尖齐',
    history: '湖笔产于浙江湖州，元代以后取代宣笔成为"文房四宝"之首。以"尖、齐、圆、健"四德著称，羊毫、狼毫、兼毫俱佳，自元代冯应科制笔名声大噪后，历代文人推崇备至。',
    weight: { small: 25, medium: 12, large: 4 }
  },
  {
    id: 'g-paper',
    name: '澄心笺',
    icon: '📜',
    imageUrl: 'mini-assets/gifts/icons/g-paper.png',
    photoUrl: 'mini-assets/gifts/photos/g-paper.jpg',
    rarity: 1,
    type: '笔墨纸砚',
    dynasty: 'wudai',
    dynastyName: '南唐',
    desc: '南唐澄心堂纸，光洁如玉',
    history: '南唐后主李煜督办所造，取名的澄心堂为李煜读书处。此纸"肤如卵膜，坚洁如玉"，一纸值百钱，是中国造纸史上的巅峰之作，后世仿制不断。',
    weight: { small: 22, medium: 14, large: 3 }
  },
  {
    id: 'g-huimo',
    name: '徽墨',
    icon: '🖤',
    imageUrl: 'mini-assets/gifts/icons/g-huimo.png',
    photoUrl: 'mini-assets/gifts/photos/g-huimo.jpg',
    rarity: 2,
    type: '笔墨纸砚',
    dynasty: 'song',
    dynastyName: '宋代',
    desc: '徽州松烟，墨色如漆',
    history: '宋代宣和年间徽州制墨名家辈出，以松烟、油烟为主要原料，配以麝香、冰片等名贵香料。徽墨"落纸如漆，万载存真"，被誉为"千秋光洁，研露调松"。',
    weight: { small: 8, medium: 18, large: 7 }
  },
  {
    id: 'g-duanyan',
    name: '端砚',
    icon: '🪨',
    imageUrl: 'mini-assets/gifts/icons/g-duanyan.png',
    photoUrl: 'mini-assets/gifts/photos/g-duanyan.jpg',
    rarity: 2,
    type: '笔墨纸砚',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '天下第一砚，石眼生动',
    history: '端砚产于广东肇庆斧柯山端溪，唐代已列为贡品。石质温润如玉，磨之无声，发墨不损毫。以有"石眼"者为贵，天然花纹如鸲鹆眼、鹦哥眼，栩栩如生。',
    weight: { small: 6, medium: 20, large: 8 }
  },
  {
    id: 'g-xuanpaper',
    name: '宣纸',
    icon: '📄',
    imageUrl: 'mini-assets/gifts/icons/g-xuanpaper.png',
    photoUrl: 'mini-assets/gifts/photos/g-xuanpaper.jpg',
    rarity: 1,
    type: '笔墨纸砚',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '纸寿千年，润墨如神',
    history: '宣纸产于安徽泾县，以青檀树皮为主要原料，唐代已为贡品。其特点是"薄如蝉翼，韧如肌肤"，着墨层次分明，历千年而不脆，素有"纸寿千年"之誉。',
    weight: { small: 28, medium: 10, large: 5 }
  },
  {
    id: 'g-langhao',
    name: '狼毫笔',
    icon: '🖊️',
    imageUrl: 'mini-assets/gifts/icons/g-langhao.png',
    photoUrl: 'mini-assets/gifts/photos/g-langhao.jpg',
    rarity: 1,
    type: '笔墨纸砚',
    dynasty: 'ming',
    dynastyName: '明代',
    desc: '黄鼠狼尾毫，弹性十足',
    history: '狼毫以黄鼠狼尾毛制成，非狼毛。笔锋劲健挺拔，适合写小楷和工笔白描。明代制笔工艺成熟，湖州、苏州一带狼毫笔品质最佳，为文人案头必备。',
    weight: { small: 20, medium: 13, large: 4 }
  },
  {
    id: 'g-songmo',
    name: '松烟墨',
    icon: '⬛',
    imageUrl: 'mini-assets/gifts/icons/g-songmo.png',
    photoUrl: 'mini-assets/gifts/photos/g-songmo.jpg',
    rarity: 1,
    type: '笔墨纸砚',
    dynasty: 'han',
    dynastyName: '汉代',
    desc: '焚松取烟，最古墨法',
    history: '松烟墨是中国最早的制墨法，焚烧松木取烟炱，再以胶拌和成型。汉代已有成熟工艺，出土汉墨呈丸状、块状。此墨色黑而沉，宜书不宜画。',
    weight: { small: 26, medium: 11, large: 3 }
  },
  {
    id: 'g-sheyan',
    name: '歙砚',
    icon: '⛰️',
    imageUrl: 'mini-assets/gifts/icons/g-sheyan.png',
    photoUrl: 'mini-assets/gifts/photos/g-sheyan.jpg',
    rarity: 2,
    type: '笔墨纸砚',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '龙尾石砚，金星罗纹',
    history: '歙砚产于安徽歙县龙尾山，又称龙尾砚。石色苍黑，天然纹理有金星、银星、罗纹、眉子等。南唐后主李煜赞为"天下冠"，与端砚并称"二大砚"。',
    weight: { small: 5, medium: 16, large: 6 }
  },
  {
    id: 'g-yuguanbi',
    name: '玉管毛笔',
    icon: '✒️',
    imageUrl: 'mini-assets/gifts/icons/g-yuguanbi.png',
    photoUrl: 'mini-assets/gifts/photos/g-yuguanbi.jpg',
    rarity: 3,
    type: '笔墨纸砚',
    dynasty: 'ming',
    dynastyName: '明代',
    desc: '白玉笔管，宫廷御用',
    history: '明代宫廷御用文房，笔管以和田白玉雕琢，刻龙凤纹或花卉纹。明代永宣时期制笔工艺精湛，定陵曾出土玉管毛笔，为帝皇日常书写用具。',
    weight: { small: 2, medium: 6, large: 14 }
  },
  {
    id: 'g-xiangyabi',
    name: '象牙管毛笔',
    icon: '✒️',
    imageUrl: 'mini-assets/gifts/icons/g-xiangyabi.png',
    photoUrl: 'mini-assets/gifts/photos/g-xiangyabi.jpg',
    rarity: 3,
    type: '笔墨纸砚',
    dynasty: 'qing',
    dynastyName: '清代',
    desc: '象牙雕管，造办处制',
    history: '清代造办处精制御笔，笔管以象牙为材，上刻山水人物或花卉翎毛。象牙温润细腻，宜雕宜刻，为清宫文房代表性器物。',
    weight: { small: 1, medium: 5, large: 12 }
  },

  // ========== 茶酒食（10件） ==========
  {
    id: 'g-tea',
    name: '顾渚紫笋',
    icon: '🍵',
    imageUrl: 'mini-assets/gifts/icons/g-tea.png',
    photoUrl: 'mini-assets/gifts/photos/g-tea.jpg',
    rarity: 2,
    type: '茶酒食',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '唐代贡茶，紫笋飘香',
    history: '产于浙江长兴顾渚山，陆羽《茶经》推为上品。唐代宗大历五年起为贡茶，每年清明前急递长安，谓之"急递茶"。紫笋茶芽色紫而形似笋，故名。',
    weight: { small: 10, medium: 14, large: 5 }
  },
  {
    id: 'g-wine',
    name: '剑南烧春',
    icon: '🍶',
    imageUrl: 'mini-assets/gifts/icons/g-wine.png',
    photoUrl: 'mini-assets/gifts/photos/g-wine.jpg',
    rarity: 3,
    type: '茶酒食',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '唐时名酒，剑南春前身',
    history: '唐代剑南道（今四川绵竹）所产名酒，李肇《唐国史补》列为天下名酒之一。"烧春"即烧酒，唐代已有蒸馏酒雏形。剑南烧春为宫廷贡酒，今剑南春酒即沿此名。',
    weight: { small: 3, medium: 7, large: 15 }
  },
  {
    id: 'g-snack',
    name: '水晶点心',
    icon: '🍡',
    imageUrl: 'mini-assets/gifts/icons/g-snack.png',
    photoUrl: 'mini-assets/gifts/photos/g-snack.jpg',
    rarity: 1,
    type: '茶酒食',
    dynasty: 'song',
    dynastyName: '宋代',
    desc: '宋代茶肆点心，玲珑剔透',
    history: '宋代市井繁华，茶肆酒楼遍布汴京临安。水晶点心以澄面或豆粉制成，半透明如水晶，为茶肆佐茶佳品。《东京梦华录》《武林旧事》均有记载。',
    weight: { small: 18, medium: 15, large: 2 }
  },
  {
    id: 'g-incense',
    name: '鹅梨帐香',
    icon: '🪔',
    imageUrl: 'mini-assets/gifts/icons/g-incense.png',
    photoUrl: 'mini-assets/gifts/photos/g-incense.jpg',
    rarity: 2,
    type: '茶酒食',
    dynasty: 'song',
    dynastyName: '宋代',
    desc: '江南合香，清幽入梦',
    history: '宋代江南流行的合香方，以鹅梨汁和沉香末制成。焚之清幽淡雅，置于床帐间可助眠安神。李清照词中"瑞脑销金兽"即此类香事。',
    weight: { small: 7, medium: 19, large: 6 }
  },
  {
    id: 'g-longfengtea',
    name: '龙凤团茶',
    icon: '🍵',
    imageUrl: 'mini-assets/gifts/icons/g-longfengtea.png',
    photoUrl: 'mini-assets/gifts/photos/g-longfengtea.jpg',
    rarity: 3,
    type: '茶酒食',
    dynasty: 'beisong',
    dynastyName: '北宋',
    desc: '北宋贡茶，龙凤模印',
    history: '北宋丁谓、蔡襄先后监制，以龙凤模印压制成饼。每片重二十两，专供宫廷。欧阳修云"金可有而茶不可得"，一饼值黄金二两，为宋代茶文化巅峰。',
    weight: { small: 2, medium: 8, large: 16 }
  },
  {
    id: 'g-yinchaju',
    name: '银鎏金茶具',
    icon: '🍵',
    imageUrl: 'mini-assets/gifts/icons/g-yinchaju.png',
    photoUrl: 'mini-assets/gifts/photos/g-yinchaju.jpg',
    rarity: 4,
    type: '茶酒食',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '法门寺地宫出土，唐代宫廷茶具',
    history: '1987年陕西法门寺地宫出土，为唐僖宗供奉的银鎏金茶具一套，含茶碾、茶罗、盐台、匙等。是现存最完整的唐代宫廷茶具，印证了陆羽《茶经》所述煎茶法。',
    weight: { small: 0, medium: 2, large: 7 }
  },
  {
    id: 'g-tuhaozhan',
    name: '兔毫盏',
    icon: '🍵',
    imageUrl: 'mini-assets/gifts/icons/g-tuhaozhan.png',
    photoUrl: 'mini-assets/gifts/photos/g-tuhaozhan.jpg',
    rarity: 2,
    type: '茶酒食',
    dynasty: 'song',
    dynastyName: '宋代',
    desc: '建窑黑釉，斗茶利器',
    history: '福建建阳建窑所产黑釉茶盏，釉面呈兔毫状条纹。宋代斗茶之风盛行，蔡襄《茶录》云"茶色白，宜黑盏"，兔毫盏为斗茶首选，日本称之为"天目"。',
    weight: { small: 4, medium: 17, large: 9 }
  },
  {
    id: 'g-qinghuajiu',
    name: '青花酒壶',
    icon: '🍶',
    imageUrl: 'mini-assets/gifts/icons/g-qinghuajiu.png',
    photoUrl: 'mini-assets/gifts/photos/g-qinghuajiu.jpg',
    rarity: 3,
    type: '茶酒食',
    dynasty: 'yuan',
    dynastyName: '元代',
    desc: '元青花缠枝纹，酒器精品',
    history: '元代景德镇青花瓷酒壶，以钴料绘缠枝莲纹，白地蓝花。元青花是中国陶瓷史上的里程碑，存世稀少，每一件都价值连城。',
    weight: { small: 1, medium: 6, large: 13 }
  },
  {
    id: 'g-liuli',
    name: '琉璃葡萄',
    icon: '🍇',
    imageUrl: 'mini-assets/gifts/icons/g-liuli.png',
    photoUrl: 'mini-assets/gifts/photos/g-liuli.jpg',
    rarity: 3,
    type: '茶酒食',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '唐代琉璃工艺，仿葡萄形',
    history: '唐代琉璃（玻璃）工艺品，仿葡萄串形，色彩碧绿通透。唐代琉璃受波斯萨珊王朝影响，工艺精美。西安何家村出土有唐代琉璃器，为丝路贸易的见证。',
    weight: { small: 0, medium: 4, large: 10 }
  },
  {
    id: 'g-wumahuci',
    name: '鎏金舞马衔杯壶',
    icon: '🐎',
    imageUrl: 'mini-assets/gifts/icons/g-wumahuci.png',
    photoUrl: 'mini-assets/gifts/photos/g-wumahuci.jpg',
    rarity: 4,
    type: '茶酒食',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '何家村窖藏，玄宗千秋节',
    history: '1970年西安何家村出土，银质鎏金，壶身錾刻舞马衔杯图案。唐玄宗千秋节时宫廷舞马数百匹随乐起舞，衔杯祝寿。此壶为现存唯一舞马形象实物。',
    weight: { small: 0, medium: 1, large: 6 }
  },

  // ========== 玉器（10件） ==========
  {
    id: 'g-jade',
    name: '螭纹玉佩',
    icon: '💎',
    imageUrl: 'mini-assets/gifts/icons/g-jade.png',
    photoUrl: 'mini-assets/gifts/photos/g-jade.jpg',
    rarity: 2,
    type: '玉器',
    dynasty: 'zhanguo',
    dynastyName: '战国',
    desc: '和田白玉，螭龙穿云',
    history: '战国时期典型玉佩，以和田白玉雕琢，纹饰为螭龙穿云。战国玉器工艺精湛，镂空、浅浮雕俱佳，螭龙纹为当时流行纹饰，象征权力与祥瑞。',
    weight: { small: 9, medium: 15, large: 7 }
  },
  {
    id: 'g-yubi',
    name: '玉璧',
    icon: '⭕',
    imageUrl: 'mini-assets/gifts/icons/g-yubi.png',
    photoUrl: 'mini-assets/gifts/photos/g-yubi.jpg',
    rarity: 3,
    type: '玉器',
    dynasty: 'xianqin',
    dynastyName: '良渚',
    desc: '新石器礼器，苍璧礼天',
    history: '良渚文化（约公元前3300年）玉璧，"以苍璧礼天"为六器之首。良渚玉器以软玉为材，璧呈扁平圆环形，中间有孔，是原始宗教礼器，反映早期中华文明。',
    weight: { small: 2, medium: 7, large: 17 }
  },
  {
    id: 'g-yucong',
    name: '玉琮',
    icon: '🔲',
    imageUrl: 'mini-assets/gifts/icons/g-yucong.png',
    photoUrl: 'mini-assets/gifts/photos/g-yucong.jpg',
    rarity: 4,
    type: '玉器',
    dynasty: 'xianqin',
    dynastyName: '良渚',
    desc: '良渚文化代表，黄琮礼地',
    history: '良渚文化玉琮，外方内圆，象征"天圆地方"。表面刻神人兽面纹，为良渚先民祭祀天地的核心礼器。良渚玉琮是中华五千年文明的实证，2019年良渚古城遗址列入世界遗产。',
    weight: { small: 0, medium: 2, large: 8 }
  },
  {
    id: 'g-yuhuang',
    name: '龙纹玉璜',
    icon: '🌙',
    imageUrl: 'mini-assets/gifts/icons/g-yuhuang.png',
    photoUrl: 'mini-assets/gifts/photos/g-yuhuang.jpg',
    rarity: 3,
    type: '玉器',
    dynasty: 'xizhou',
    dynastyName: '西周',
    desc: '西周礼玉，双龙首纹',
    history: '西周时期玉璜，呈半璧形，两端雕龙首。璜为"六器"之一，"以玄璜礼北方"。西周玉器纹饰以双阴线一坡刀法为特征，龙纹庄严神秘。',
    weight: { small: 3, medium: 8, large: 14 }
  },
  {
    id: 'g-yuxi',
    name: '玉觿',
    icon: '🔑',
    imageUrl: 'mini-assets/gifts/icons/g-yuxi.png',
    photoUrl: 'mini-assets/gifts/photos/g-yuxi.jpg',
    rarity: 1,
    type: '玉器',
    dynasty: 'chunqiu',
    dynastyName: '春秋',
    desc: '解绳工具兼佩饰',
    history: '春秋时期玉觿，形如角锥，最初为解绳结的实用工具，后演变为佩饰。"觿"字从角从巂，象征成年后能决断是非。诗经有"芄兰之支，童子佩觿"之句。',
    weight: { small: 24, medium: 9, large: 4 }
  },
  {
    id: 'g-yudaiou',
    name: '玉带钩',
    icon: '🪢',
    imageUrl: 'mini-assets/gifts/icons/g-yudaiou.png',
    photoUrl: 'mini-assets/gifts/photos/g-yudaiou.jpg',
    rarity: 2,
    type: '玉器',
    dynasty: 'zhanguo',
    dynastyName: '战国',
    desc: '战国贵族腰带扣，鎏金嵌玉',
    history: '战国时期贵族所用带钩，以铜为胎，鎏金嵌玉。带钩是古代束腰皮带的扣件，战国至汉代流行，材质从铜到金玉不等。曾侯乙墓出土有金玉带钩，极为精美。',
    weight: { small: 6, medium: 21, large: 8 }
  },
  {
    id: 'g-yuren',
    name: '玉人',
    icon: '🗿',
    imageUrl: 'mini-assets/gifts/icons/g-yuren.png',
    photoUrl: 'mini-assets/gifts/photos/g-yuren.jpg',
    rarity: 3,
    type: '玉器',
    dynasty: 'shang',
    dynastyName: '商代',
    desc: '殷墟出土玉雕人像',
    history: '商代殷墟出土玉人，以青玉或白玉雕琢，人物跽坐或站立，衣着发式写实。商代玉人是中国最早的玉雕人像之一，反映了商代社会生活和服饰制度。妇好墓出土玉人最为著名。',
    weight: { small: 1, medium: 5, large: 11 }
  },
  {
    id: 'g-zigang',
    name: '子冈牌',
    icon: '🎴',
    imageUrl: 'mini-assets/gifts/icons/g-zigang.png',
    photoUrl: 'mini-assets/gifts/photos/g-zigang.jpg',
    rarity: 3,
    type: '玉器',
    dynasty: 'ming',
    dynastyName: '明代',
    desc: '陆子冈治玉，山水诗文',
    history: '明代治玉大师陆子冈所制玉牌，一面刻山水人物，一面刻诗文落款。子冈牌开创了玉雕诗书画印合一的先河，后世仿制不绝，为文人玉雕的巅峰。',
    weight: { small: 2, medium: 6, large: 12 }
  },
  {
    id: 'g-feicui',
    name: '翡翠白菜',
    icon: '🥬',
    imageUrl: 'mini-assets/gifts/icons/g-feicui.png',
    photoUrl: 'mini-assets/gifts/photos/g-feicui.jpg',
    rarity: 4,
    type: '玉器',
    dynasty: 'qing',
    dynastyName: '清代',
    desc: '清代玉雕极品，台北故宫藏',
    history: '清代翠玉白菜，以一块半白半绿的翡翠原石巧雕而成，绿色部分雕为菜叶，白色部分雕为菜帮，叶上停有螽斯和蝗虫，寓意多子多孙。原陈设于光绪帝瑾妃寝宫，现为台北故宫镇馆之宝。',
    weight: { small: 0, medium: 1, large: 5 }
  },
  {
    id: 'g-ruyi',
    name: '玉如意',
    icon: '☸️',
    imageUrl: 'mini-assets/gifts/icons/g-ruyi.png',
    photoUrl: 'mini-assets/gifts/photos/g-ruyi.jpg',
    rarity: 2,
    type: '玉器',
    dynasty: 'qing',
    dynastyName: '清代',
    desc: '清宫陈设，吉祥寓意',
    history: '如意原为搔杖，清代演变为陈设品和赏赐品。以整块和田玉雕琢，头部呈灵芝或云形，柄身刻浮雕山水花卉。清代皇帝常以玉如意赏赐大臣和外国使节。',
    weight: { small: 8, medium: 16, large: 6 }
  },

  // ========== 青铜器（10件） ==========
  {
    id: 'g-bronze',
    name: '商周青铜爵',
    icon: '🍷',
    imageUrl: 'mini-assets/gifts/icons/g-bronze.png',
    photoUrl: 'mini-assets/gifts/photos/g-bronze.jpg',
    rarity: 3,
    type: '青铜器',
    dynasty: 'shang',
    dynastyName: '商代',
    desc: '三足酒器，饕餮纹饰',
    history: '商代青铜爵，饮酒器，前有流后有尾，口沿有柱，腹饰饕餮纹。爵是青铜礼器中最基本的酒器，商代"重酒"文化下大量铸造，为贵族宴飨和祭祀必备。',
    weight: { small: 2, medium: 7, large: 16 }
  },
  {
    id: 'g-tongding',
    name: '青铜鼎',
    icon: '🍲',
    imageUrl: 'mini-assets/gifts/icons/g-tongding.png',
    photoUrl: 'mini-assets/gifts/photos/g-tongding.jpg',
    rarity: 3,
    type: '青铜器',
    dynasty: 'xizhou',
    dynastyName: '西周',
    desc: '三足圆鼎，列鼎制度',
    history: '西周青铜鼎，烹煮和盛放肉食的礼器。周代有严格的列鼎制度：天子九鼎、诸侯七鼎、大夫五鼎、士三鼎或一鼎。鼎是国家权力的象征，"问鼎中原"即出于此。',
    weight: { small: 3, medium: 8, large: 18 }
  },
  {
    id: 'g-tonggui',
    name: '青铜簋',
    icon: '🥣',
    imageUrl: 'mini-assets/gifts/icons/g-tonggui.png',
    photoUrl: 'mini-assets/gifts/photos/g-tonggui.jpg',
    rarity: 2,
    type: '青铜器',
    dynasty: 'xizhou',
    dynastyName: '西周',
    desc: '盛食器，圆腹双耳',
    history: '西周青铜簋，盛放黍稷的礼器，圆腹圈足双耳。簋与鼎配组使用，天子用九鼎八簋。西周簋造型庄重，纹饰以窃曲纹、环带纹为主，是周代礼制的重要载体。',
    weight: { small: 8, medium: 18, large: 6 }
  },
  {
    id: 'g-tonggu',
    name: '青铜觚',
    icon: '🥂',
    imageUrl: 'mini-assets/gifts/icons/g-tonggu.png',
    photoUrl: 'mini-assets/gifts/photos/g-tonggu.jpg',
    rarity: 2,
    type: '青铜器',
    dynasty: 'shang',
    dynastyName: '商代',
    desc: '饮酒器，喇叭口细腰',
    history: '商代青铜觚，饮酒器，喇叭口、细腰、高圈足。觚与爵常成组出土，为商代"重酒"组合的核心器物。商代觚造型修长优雅，纹饰繁缛，体现了商代铸造工艺的精湛。',
    weight: { small: 7, medium: 16, large: 7 }
  },
  {
    id: 'g-tongjian',
    name: '青铜剑',
    icon: '⚔️',
    imageUrl: 'mini-assets/gifts/icons/g-tongjian.png',
    photoUrl: 'mini-assets/gifts/photos/g-tongjian.jpg',
    rarity: 3,
    type: '青铜器',
    dynasty: 'zhanguo',
    dynastyName: '战国',
    desc: '越王勾践剑，千年不锈',
    history: '1965年湖北江陵望山楚墓出土，剑身刻"越王鸠浅自作用剑"鸟篆铭文。剑身布满菱形暗纹，刃部锋利如新，出土时尚能划破纸张。表面经硫化处理，千年不锈，是世界冶金史上的奇迹。',
    weight: { small: 1, medium: 6, large: 13 }
  },
  {
    id: 'g-tongjing',
    name: '青铜镜',
    icon: '🪞',
    imageUrl: 'mini-assets/gifts/icons/g-tongjing.png',
    photoUrl: 'mini-assets/gifts/photos/g-tongjing.jpg',
    rarity: 2,
    type: '青铜器',
    dynasty: 'han',
    dynastyName: '汉代',
    desc: '汉代铜镜，日光连弧纹',
    history: '汉代青铜镜，背面铸有日光连弧纹和铭文"见日之光，天下大明"。汉代铜镜铸造工艺成熟，镜面平整，照影清晰。汉代镜铭文多为吉祥语，反映了汉人的宇宙观。',
    weight: { small: 5, medium: 20, large: 8 }
  },
  {
    id: 'g-simuwuding',
    name: '司母戊鼎',
    icon: '🏺',
    imageUrl: 'mini-assets/gifts/icons/g-simuwuding.png',
    photoUrl: 'mini-assets/gifts/photos/g-simuwuding.jpg',
    rarity: 4,
    type: '青铜器',
    dynasty: 'shang',
    dynastyName: '商代',
    desc: '后母戊鼎，世界最大青铜器',
    history: '1939年河南安阳殷墟出土，高133厘米，重832.84公斤，是现存最大的青铜器。鼎内壁铸"后母戊"三字铭文，为商王祖庚或祖甲为祭祀母亲戊所铸。现藏中国国家博物馆，为国家一级文物。',
    weight: { small: 0, medium: 2, large: 8 }
  },
  {
    id: 'g-siyangfangzun',
    name: '四羊方尊',
    icon: '🐏',
    imageUrl: 'mini-assets/gifts/icons/g-siyangfangzun.png',
    photoUrl: 'mini-assets/gifts/photos/g-siyangfangzun.jpg',
    rarity: 4,
    type: '青铜器',
    dynasty: 'shang',
    dynastyName: '商代',
    desc: '商代酒器，羊角峥嵘',
    history: '1938年湖南宁乡出土，商代方尊，四角铸大卷角羊头。羊为祥瑞之兽，"四羊"寓意四方吉祥。铸造采用分铸法，先铸羊头再合范浇铸器身，工艺极为复杂，是商代青铜艺术巅峰之作。',
    weight: { small: 0, medium: 1, large: 6 }
  },
  {
    id: 'g-maogongding',
    name: '毛公鼎',
    icon: '📜',
    imageUrl: 'mini-assets/gifts/icons/g-maogongding.png',
    photoUrl: 'mini-assets/gifts/photos/g-maogongding.jpg',
    rarity: 3,
    type: '青铜器',
    dynasty: 'xizhou',
    dynastyName: '西周',
    desc: '铭文最长青铜器，499字',
    history: '西周晚期青铜鼎，清道光年间陕西岐山出土。内壁铸有499字铭文，是现存铭文最长的青铜器。铭文为周宣王册命毛公瘖的诰辞，涉及西周晚期政治军事，是研究西周史的第一手史料。现藏台北故宫。',
    weight: { small: 2, medium: 7, large: 15 }
  },
  {
    id: 'g-bianzhong',
    name: '曾侯乙编钟',
    icon: '🔔',
    imageUrl: 'mini-assets/gifts/icons/g-bianzhong.png',
    photoUrl: 'mini-assets/gifts/photos/g-bianzhong.jpg',
    rarity: 2,
    type: '青铜器',
    dynasty: 'zhanguo',
    dynastyName: '战国',
    desc: '65件套，一钟双音',
    history: '1978年湖北随州曾侯乙墓出土，由65件青铜钟组成，分八组悬挂于三层钟架。每件钟可发两个不同音高，全套音域跨五个半八度，能演奏完整的十二半音阶乐曲。是中国先秦音乐文化的巅峰之作。',
    weight: { small: 3, medium: 22, large: 9 }
  },

  // ========== 陶瓷（10件） ==========
  {
    id: 'g-pottery',
    name: '越窑青瓷',
    icon: '🏺',
    imageUrl: 'mini-assets/gifts/icons/g-pottery.png',
    photoUrl: 'mini-assets/gifts/photos/g-pottery.jpg',
    rarity: 2,
    type: '陶瓷',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '秘色瓷盏，千峰翠色',
    history: '越窑产于浙江余姚上林湖，唐代为贡瓷。釉色青绿，如冰似玉，陆羽《茶经》评为"类玉""类冰"。晚唐五代时期达到巅峰，"秘色瓷"为越窑最高品种，法门寺地宫曾出土。',
    weight: { small: 9, medium: 17, large: 6 }
  },
  {
    id: 'g-longquan',
    name: '龙泉窑青瓷',
    icon: '🏺',
    imageUrl: 'mini-assets/gifts/icons/g-longquan.png',
    photoUrl: 'mini-assets/gifts/photos/g-longquan.jpg',
    rarity: 3,
    type: '陶瓷',
    dynasty: 'nansong',
    dynastyName: '南宋',
    desc: '梅子青釉，如冰似玉',
    history: '南宋龙泉窑产于浙江龙泉，以粉青、梅子青釉色著称。釉层丰厚肥润，如堆脂凝翠，为青瓷工艺巅峰。龙泉窑青瓷远销海外，从海上丝绸之路销往亚非欧，影响深远。',
    weight: { small: 2, medium: 5, large: 11 }
  },
  {
    id: 'g-junyao',
    name: '钧窑碗',
    icon: '🥣',
    imageUrl: 'mini-assets/gifts/icons/g-junyao.png',
    photoUrl: 'mini-assets/gifts/photos/g-junyao.jpg',
    rarity: 3,
    type: '陶瓷',
    dynasty: 'beisong',
    dynastyName: '北宋',
    desc: '入窑一色，出窑万彩',
    history: '北宋钧窑产于河南禹州，以铜红釉窑变著称。釉色有天青、月白、海棠红、玫瑰紫等，"入窑一色，出窑万彩"，每件独一无二。钧窑为宋代五大名窑之一。',
    weight: { small: 3, medium: 7, large: 14 }
  },
  {
    id: 'g-ruyao',
    name: '汝窑天青釉',
    icon: '💠',
    imageUrl: 'mini-assets/gifts/icons/g-ruyao.png',
    photoUrl: 'mini-assets/gifts/photos/g-ruyao.jpg',
    rarity: 4,
    type: '陶瓷',
    dynasty: 'beisong',
    dynastyName: '北宋',
    desc: '雨过天青云破处',
    history: '北宋汝窑产于河南汝州，为五大名窑之首。釉色天青，"雨过天青云破处，这般颜色做将来"。存世不足百件，每件均为无价之宝。汝窑釉面有细密开片，如蟹爪冰裂，为自然天成之美。',
    weight: { small: 0, medium: 2, large: 7 }
  },
  {
    id: 'g-dingyao',
    name: '定窑白瓷',
    icon: '🍽️',
    imageUrl: 'mini-assets/gifts/icons/g-dingyao.png',
    photoUrl: 'mini-assets/gifts/photos/g-dingyao.jpg',
    rarity: 2,
    type: '陶瓷',
    dynasty: 'beisong',
    dynastyName: '北宋',
    desc: '刻花白瓷，牙白温润',
    history: '北宋定窑产于河北曲阳，以白釉刻花著称。釉色牙白温润，纹饰以牡丹、莲荷、游鱼为主，刀法流畅。定窑首创覆烧工艺，产量大增，为宋代使用最广的瓷器。',
    weight: { small: 8, medium: 19, large: 7 }
  },
  {
    id: 'g-jianyao',
    name: '建窑黑釉盏',
    icon: '🍵',
    imageUrl: 'mini-assets/gifts/icons/g-jianyao.png',
    photoUrl: 'mini-assets/gifts/photos/g-jianyao.jpg',
    rarity: 2,
    type: '陶瓷',
    dynasty: 'nansong',
    dynastyName: '南宋',
    desc: '兔毫油滴，斗茶首选',
    history: '南宋建窑产于福建建阳，黑釉茶盏。釉面结晶呈兔毫纹、油滴纹等，在光照下闪烁银光。宋代斗茶之风盛行，黑釉盏最能衬托白色茶沫，为茶人珍品。',
    weight: { small: 6, medium: 18, large: 8 }
  },
  {
    id: 'g-yuanqinghua',
    name: '元青花瓶',
    icon: '🏺',
    imageUrl: 'mini-assets/gifts/icons/g-yuanqinghua.png',
    photoUrl: 'mini-assets/gifts/photos/g-yuanqinghua.jpg',
    rarity: 4,
    type: '陶瓷',
    dynasty: 'yuan',
    dynastyName: '元代',
    desc: '鬼谷子下山图罐',
    history: '元代景德镇青花瓷，以钴料在白胎上绘制纹饰，施透明釉高温烧成。元青花存世稀少，2005年伦敦佳士得拍卖的"鬼谷子下山"图罐以2.3亿元成交，创中国艺术品拍卖纪录。',
    weight: { small: 0, medium: 1, large: 5 }
  },
  {
    id: 'g-mingqinghua',
    name: '明青花碗',
    icon: '🥣',
    imageUrl: 'mini-assets/gifts/icons/g-mingqinghua.png',
    photoUrl: 'mini-assets/gifts/photos/g-mingqinghua.jpg',
    rarity: 1,
    type: '陶瓷',
    dynasty: 'ming',
    dynastyName: '明代',
    desc: '永乐青花缠枝莲纹',
    history: '明代永乐时期景德镇青花碗，以苏麻离青料绘制缠枝莲纹。永乐青花呈色浓艳，有铁锈斑晕散效果，为明代青花瓷的代表。器形规整，纹饰流畅。',
    weight: { small: 21, medium: 12, large: 5 }
  },
  {
    id: 'g-dehua',
    name: '德化白瓷',
    icon: '🗿',
    imageUrl: 'mini-assets/gifts/icons/g-dehua.png',
    photoUrl: 'mini-assets/gifts/photos/g-dehua.jpg',
    rarity: 3,
    type: '陶瓷',
    dynasty: 'ming',
    dynastyName: '明代',
    desc: '何朝宗款白瓷观音',
    history: '明代福建德化窑白瓷，以何朝宗所制观音、达摩像最为著名。釉色乳白如凝脂，又称"猪油白""象牙白"。德化白瓷远销欧洲，被法国人称为"中国白"(Blanc de Chine)。',
    weight: { small: 1, medium: 5, large: 12 }
  },
  {
    id: 'g-fencai',
    name: '粉彩瓷瓶',
    icon: '🏺',
    imageUrl: 'mini-assets/gifts/icons/g-fencai.png',
    photoUrl: 'mini-assets/gifts/photos/g-fencai.jpg',
    rarity: 3,
    type: '陶瓷',
    dynasty: 'qing',
    dynastyName: '清代',
    desc: '雍正粉彩，柔美细腻',
    history: '清代雍正时期景德镇粉彩瓷，以玻璃白打底，色彩柔和粉润。雍正粉彩以花卉、花鸟为题材，构图疏朗，设色淡雅，代表了清代彩瓷的最高水平。',
    weight: { small: 2, medium: 6, large: 13 }
  },

  // ========== 金银器（10件） ==========
  {
    id: 'g-jinbuyao',
    name: '金步摇',
    icon: '👑',
    imageUrl: 'mini-assets/gifts/icons/g-jinbuyao.png',
    photoUrl: 'mini-assets/gifts/photos/g-jinbuyao.jpg',
    rarity: 3,
    type: '金银器',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '唐代贵族头饰，金叶摇曳',
    history: '唐代贵族妇女头饰，以金丝编缀花叶，行走时随步摇曳，故名"步摇"。唐代金步摇工艺精湛，掐丝、累丝、镶嵌俱佳。西安何家村窖藏出土有金步摇残件。',
    weight: { small: 2, medium: 7, large: 15 }
  },
  {
    id: 'g-yinfazan',
    name: '银鎏金发簪',
    icon: '📌',
    imageUrl: 'mini-assets/gifts/icons/g-yinfazan.png',
    photoUrl: 'mini-assets/gifts/photos/g-yinfazan.jpg',
    rarity: 2,
    type: '金银器',
    dynasty: 'ming',
    dynastyName: '明代',
    desc: '掐丝累丝工艺，精美绝伦',
    history: '明代银鎏金发簪，以掐丝、累丝工艺制成花卉飞鸟纹样。明代金银饰品工艺登峰造极，定陵出土的金簪银簪代表了当时最高工艺水平。',
    weight: { small: 7, medium: 15, large: 6 }
  },
  {
    id: 'g-jinwan',
    name: '金碗',
    icon: '🥣',
    imageUrl: 'mini-assets/gifts/icons/g-jinwan.png',
    photoUrl: 'mini-assets/gifts/photos/g-jinwan.jpg',
    rarity: 3,
    type: '金银器',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '法门寺出土金钵盂',
    history: '1987年陕西法门寺地宫出土，纯金锤揲成型，口沿刻莲瓣纹。唐代金器以锤揲、錾刻为主，造型饱满。此碗为唐僖宗供奉佛骨舍利的器具之一。',
    weight: { small: 1, medium: 6, large: 12 }
  },
  {
    id: 'g-yinxunlu',
    name: '银熏炉',
    icon: '⚱️',
    imageUrl: 'mini-assets/gifts/icons/g-yinxunlu.png',
    photoUrl: 'mini-assets/gifts/photos/g-yinxunlu.jpg',
    rarity: 2,
    type: '金银器',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '鎏金银熏球，球形链挂',
    history: '唐代鎏金银熏球，球形容器内设万向轴承，无论怎样翻转香灰不洒。1963年西安沙坡村出土的唐代银熏球工艺精绝，反映了唐代机械工艺与金银加工的高超水平。',
    weight: { small: 5, medium: 21, large: 9 }
  },
  {
    id: 'g-jinlong',
    name: '金龙',
    icon: '🐉',
    imageUrl: 'mini-assets/gifts/icons/g-jinlong.png',
    photoUrl: 'mini-assets/gifts/photos/g-jinlong.jpg',
    rarity: 4,
    type: '金银器',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '何家村出土赤金走龙',
    history: '1970年西安何家村出土，纯金铸造，高2.7厘米，作行走状。共出土12条，可能为道教投龙仪式所用。金龙造型生动，鳞甲分明，是唐代金器中的珍品。',
    weight: { small: 0, medium: 2, large: 6 }
  },
  {
    id: 'g-yinhu',
    name: '银壶',
    icon: '🦌',
    imageUrl: 'mini-assets/gifts/icons/g-yinhu.png',
    photoUrl: 'mini-assets/gifts/photos/g-yinhu.jpg',
    rarity: 3,
    type: '金银器',
    dynasty: 'liao',
    dynastyName: '辽代',
    desc: '鎏金鹿纹银壶，契丹风格',
    history: '辽代银质鎏金壶，壶身錾刻奔鹿纹。契丹族游牧文化影响下，辽代金银器兼具唐风与草原特色。此壶造型浑圆，便于马上携带，反映了契丹贵族的生活习俗。',
    weight: { small: 3, medium: 8, large: 16 }
  },
  {
    id: 'g-jinhua',
    name: '金花簪',
    icon: '🌸',
    imageUrl: 'mini-assets/gifts/icons/g-jinhua.png',
    photoUrl: 'mini-assets/gifts/photos/g-jinhua.jpg',
    rarity: 2,
    type: '金银器',
    dynasty: 'song',
    dynastyName: '宋代',
    desc: '宋代金饰，花卉纹',
    history: '宋代金质发簪，以打胎、掐丝工艺制成花卉纹。宋代金银器趋向世俗化、小型化，纹饰以花卉、飞鸟为主，风格写实细腻。',
    weight: { small: 10, medium: 16, large: 5 }
  },
  {
    id: 'g-yinding',
    name: '银锭',
    icon: '🪙',
    imageUrl: 'mini-assets/gifts/icons/g-yinding.png',
    photoUrl: 'mini-assets/gifts/photos/g-yinding.jpg',
    rarity: 1,
    type: '金银器',
    dynasty: 'song',
    dynastyName: '宋代',
    desc: '银两货币，束腰形',
    history: '宋代银锭，束腰形，上刻铭文记录重量和用途。宋代白银已作为货币流通，至元代正式确立银本位。银锭是研究古代货币制度的重要实物。',
    weight: { small: 19, medium: 14, large: 3 }
  },
  {
    id: 'g-jinguan',
    name: '金冠',
    icon: '👑',
    imageUrl: 'mini-assets/gifts/icons/g-jinguan.png',
    photoUrl: 'mini-assets/gifts/photos/g-jinguan.jpg',
    rarity: 4,
    type: '金银器',
    dynasty: 'ming',
    dynastyName: '明代',
    desc: '定陵出土万历金丝翼善冠',
    history: '1958年北京定陵出土，明万历皇帝所用金冠。以极细金丝编织而成，重826克，二龙戏珠纹。金丝细如发丝，编织紧密均匀，是明代金工艺的巅峰之作。',
    weight: { small: 0, medium: 1, large: 7 }
  },
  {
    id: 'g-yincha',
    name: '银茶具',
    icon: '🍵',
    imageUrl: 'mini-assets/gifts/icons/g-yincha.png',
    photoUrl: 'mini-assets/gifts/photos/g-yincha.jpg',
    rarity: 2,
    type: '金银器',
    dynasty: 'qing',
    dynastyName: '清代',
    desc: '清代银壶茶具一套',
    history: '清代银质茶具，含壶、杯、托等。清代银器工艺吸收了西洋技法，錾刻、镂空、掐丝并用。银茶具为富裕家庭待客所用，也是嫁妆中的贵重物品。',
    weight: { small: 8, medium: 18, large: 7 }
  },

  // ========== 古籍字画（10件） ==========
  {
    id: 'g-calligraphy',
    name: '兰亭序拓',
    icon: '✍️',
    imageUrl: 'mini-assets/gifts/icons/g-calligraphy.png',
    photoUrl: 'mini-assets/gifts/photos/g-calligraphy.jpg',
    rarity: 3,
    type: '古籍字画',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '神龙本拓片，天下第一行书',
    history: '东晋王羲之所作《兰亭序》原迹已随唐太宗殉葬。现存以唐冯承素摹"神龙本"最为接近原貌。此拓片为后人摹拓，保留了王羲之行书的飘逸神韵，被誉为"天下第一行书"。',
    weight: { small: 2, medium: 5, large: 11 }
  },
  {
    id: 'g-scroll',
    name: '古籍残卷',
    icon: '📜',
    imageUrl: 'mini-assets/gifts/icons/g-scroll.png',
    photoUrl: 'mini-assets/gifts/photos/g-scroll.jpg',
    rarity: 3,
    type: '古籍字画',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '敦煌遗书残页，墨迹犹新',
    history: '1900年敦煌莫高窟藏经洞发现，为5-11世纪写本。敦煌遗书总数约5万件，内容涵盖佛教经卷、道教文献、社会文书等，是研究中古中国社会的珍贵第一手资料。',
    weight: { small: 1, medium: 6, large: 13 }
  },
  {
    id: 'g-rubbing',
    name: '名家碑拓',
    icon: '🪨',
    imageUrl: 'mini-assets/gifts/icons/g-rubbing.png',
    photoUrl: 'mini-assets/gifts/photos/g-rubbing.jpg',
    rarity: 3,
    type: '古籍字画',
    dynasty: 'han',
    dynastyName: '汉代',
    desc: '汉碑原拓，金石气足',
    history: '汉代碑刻原拓，如《曹全碑》《张迁碑》等。汉隶方整雄浑，波磔分明，为后世书法圭臬。碑拓以"乌金拓""蝉翼拓"为上品，墨色均匀，字口清晰。',
    weight: { small: 2, medium: 7, large: 14 }
  },
  {
    id: 'g-zhaomengfu',
    name: '赵孟頫手札',
    icon: '✍️',
    imageUrl: 'mini-assets/gifts/icons/g-zhaomengfu.png',
    photoUrl: 'mini-assets/gifts/photos/g-zhaomengfu.jpg',
    rarity: 3,
    type: '古籍字画',
    dynasty: 'yuan',
    dynastyName: '元代',
    desc: '赵孟頫行书真迹',
    history: '元代书法大家赵孟頫行书手札，笔法圆转遒丽，世称"赵体"。赵孟頫为宋宗室后裔，入仕元朝，精通书画。其书法影响深远，与欧、颜、柳并称"楷书四大家"。',
    weight: { small: 3, medium: 8, large: 17 }
  },
  {
    id: 'g-songban',
    name: '宋版书',
    icon: '📖',
    imageUrl: 'mini-assets/gifts/icons/g-songban.png',
    photoUrl: 'mini-assets/gifts/photos/g-songban.jpg',
    rarity: 4,
    type: '古籍字画',
    dynasty: 'song',
    dynastyName: '宋代',
    desc: '一页宋版一两金',
    history: '宋代雕版印刷书籍，刻工精良，纸墨俱佳。宋版书字体端庄，校勘严谨，历来为藏书家珍重。明清以来有"一页宋版一两金"之说，现存宋版书不足五千部。',
    weight: { small: 0, medium: 2, large: 8 }
  },
  {
    id: 'g-minghuiben',
    name: '明代绘本',
    icon: '📕',
    imageUrl: 'mini-assets/gifts/icons/g-minghuiben.png',
    photoUrl: 'mini-assets/gifts/photos/g-minghuiben.jpg',
    rarity: 2,
    type: '古籍字画',
    dynasty: 'ming',
    dynastyName: '明代',
    desc: '明版木刻插画',
    history: '明代木刻版画书籍，以徽派、建阳派为代表。明万历年间版画达到巅峰，刻工细腻，构图繁复。《十竹斋画谱》《十竹斋笺谱》为明代版画代表作。',
    weight: { small: 6, medium: 14, large: 6 }
  },
  {
    id: 'g-dianshijuan',
    name: '清代殿试卷',
    icon: '📝',
    imageUrl: 'mini-assets/gifts/icons/g-dianshijuan.png',
    photoUrl: 'mini-assets/gifts/photos/g-dianshijuan.jpg',
    rarity: 2,
    type: '古籍字画',
    dynasty: 'qing',
    dynastyName: '清代',
    desc: '状元殿试策论真迹',
    history: '清代殿试试卷，以馆阁体书写，策论时务。殿试为科举最高一级，由皇帝亲自主持。试卷书法工整，内容涉及国家大政，是研究清代科举制度的重要史料。',
    weight: { small: 4, medium: 17, large: 8 }
  },
  {
    id: 'g-yanzhenqing',
    name: '祭侄稿',
    icon: '✍️',
    imageUrl: 'mini-assets/gifts/icons/g-yanzhenqing.png',
    photoUrl: 'mini-assets/gifts/photos/g-yanzhenqing.jpg',
    rarity: 4,
    type: '古籍字画',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '天下第二行书',
    history: '唐代颜真卿为祭奠在安史之乱中殉国的侄子颜季明所书。全篇悲愤激越，涂抹涂改处可见书写时的情绪起伏。被誉为"天下第二行书"，是书法史上的情感巅峰之作。',
    weight: { small: 0, medium: 1, large: 6 }
  },
  {
    id: 'g-hanshiti',
    name: '寒食帖',
    icon: '✍️',
    imageUrl: 'mini-assets/gifts/icons/g-hanshiti.png',
    photoUrl: 'mini-assets/gifts/photos/g-hanshiti.jpg',
    rarity: 4,
    type: '古籍字画',
    dynasty: 'song',
    dynastyName: '宋代',
    desc: '苏轼黄州寒食诗帖',
    history: '北宋苏轼被贬黄州时所作，内容为寒食节感怀。书法起伏跌宕，由平静而激越，被誉为"天下第三行书"。黄庭坚跋云"此书兼颜鲁公、杨少师、李西台笔意"。',
    weight: { small: 0, medium: 2, large: 7 }
  },
  {
    id: 'g-kuixue',
    name: '快雪时晴帖',
    icon: '❄️',
    imageUrl: 'mini-assets/gifts/icons/g-kuixue.png',
    photoUrl: 'mini-assets/gifts/photos/g-kuixue.jpg',
    rarity: 4,
    type: '古籍字画',
    dynasty: 'dongjin',
    dynastyName: '东晋',
    desc: '王羲之尺牍，乾隆三希之首',
    history: '东晋王羲之尺牍，内容为大雪初晴后问候友人。乾隆皇帝将此帖与王献之《中秋帖》、王珣《伯远帖》合称"三希"，藏于养心殿"三希堂"。现藏台北故宫。',
    weight: { small: 0, medium: 1, large: 5 }
  },

  // ========== 漆木竹器（10件） ==========
  {
    id: 'g-fan',
    name: '折扇',
    icon: '🪭',
    imageUrl: 'mini-assets/gifts/icons/g-fan.png',
    photoUrl: 'mini-assets/gifts/photos/g-fan.jpg',
    rarity: 2,
    type: '漆木竹器',
    dynasty: 'ming',
    dynastyName: '明代',
    desc: '苏工折扇，一面书画',
    history: '明代苏州制扇名家所制折扇，竹骨纸面，一面书画。明代折扇盛行，文人以扇面为书画载体，扇骨雕刻亦成艺术。苏州折扇以"水磨骨玉竹"为上品。',
    weight: { small: 9, medium: 19, large: 7 }
  },
  {
    id: 'g-tihong',
    name: '剔红漆盘',
    icon: '🔴',
    imageUrl: 'mini-assets/gifts/icons/g-tihong.png',
    photoUrl: 'mini-assets/gifts/photos/g-tihong.jpg',
    rarity: 3,
    type: '漆木竹器',
    dynasty: 'yuan',
    dynastyName: '元代',
    desc: '雕漆工艺，朱漆百层',
    history: '元代雕漆器，在胎体上髹涂朱漆数十层乃至百层，再雕刻纹饰。元代雕漆以张成、杨茂为名家，纹饰饱满，刀法浑厚。北京故宫藏有张成造剔红栀子纹盘。',
    weight: { small: 1, medium: 5, large: 12 }
  },
  {
    id: 'g-heiqimiao',
    name: '黑漆描金盒',
    icon: '📦',
    imageUrl: 'mini-assets/gifts/icons/g-heiqimiao.png',
    photoUrl: 'mini-assets/gifts/photos/g-heiqimiao.jpg',
    rarity: 2,
    type: '漆木竹器',
    dynasty: 'qing',
    dynastyName: '清代',
    desc: '清代宫廷漆器',
    history: '清代宫廷黑漆描金盒，黑漆为地，金粉描绘山水花卉。描金漆器在清代康乾时期达到高峰，工艺吸收了日本莳绘技法，富丽堂皇。',
    weight: { small: 7, medium: 16, large: 6 }
  },
  {
    id: 'g-luodian',
    name: '螺钿漆器',
    icon: '🐚',
    imageUrl: 'mini-assets/gifts/icons/g-luodian.png',
    photoUrl: 'mini-assets/gifts/photos/g-luodian.jpg',
    rarity: 3,
    type: '漆木竹器',
    dynasty: 'ming',
    dynastyName: '明代',
    desc: '江千里制螺钿漆器',
    history: '明代螺钿漆器名家江千里所制，以蚌壳薄片镶嵌于漆面，拼成花卉山水。薄螺钿在光照下五彩斑斓，为明代漆器一绝。',
    weight: { small: 2, medium: 6, large: 13 }
  },
  {
    id: 'g-mudiaoguanyin',
    name: '木雕观音',
    icon: '🗿',
    imageUrl: 'mini-assets/gifts/icons/g-mudiaoguanyin.png',
    photoUrl: 'mini-assets/gifts/photos/g-mudiaoguanyin.jpg',
    rarity: 3,
    type: '漆木竹器',
    dynasty: 'song',
    dynastyName: '宋代',
    desc: '宋代木雕加彩菩萨',
    history: '宋代木雕观音像，以整木圆雕，表面加彩贴金。宋代佛教造像世俗化，观音面容慈祥，身姿婀娜，衣纹流畅。宋代木雕观音是中国雕塑史上的精品。',
    weight: { small: 2, medium: 7, large: 15 }
  },
  {
    id: 'g-tanxiangshan',
    name: '檀香木扇',
    icon: '🪭',
    imageUrl: 'mini-assets/gifts/icons/g-tanxiangshan.png',
    photoUrl: 'mini-assets/gifts/photos/g-tanxiangshan.jpg',
    rarity: 2,
    type: '漆木竹器',
    dynasty: 'ming',
    dynastyName: '明代',
    desc: '苏州檀香扇，镂雕精细',
    history: '明代苏州檀香扇，以老山檀香木为骨，镂雕山水花卉。扇动时檀香幽幽，既是实用品又是艺术品。苏州檀香扇与杭扇、川扇、岳州扇并称"四大名扇"。',
    weight: { small: 8, medium: 18, large: 7 }
  },
  {
    id: 'g-qishayan',
    name: '漆砂砚',
    icon: '🪨',
    imageUrl: 'mini-assets/gifts/icons/g-qishayan.png',
    photoUrl: 'mini-assets/gifts/photos/g-qishayan.jpg',
    rarity: 2,
    type: '漆木竹器',
    dynasty: 'qing',
    dynastyName: '清代',
    desc: '卢葵生制漆砂砚',
    history: '清代扬州漆器名家卢葵生所制，以漆调和细砂为砚面，轻便耐磨。漆砂砚始于宋，盛于清，卢葵生作品最为著名，为文人所珍。',
    weight: { small: 5, medium: 15, large: 6 }
  },
  {
    id: 'g-tixiwan',
    name: '剔犀漆碗',
    icon: '🥣',
    imageUrl: 'mini-assets/gifts/icons/g-tixiwan.png',
    photoUrl: 'mini-assets/gifts/photos/g-tixiwan.jpg',
    rarity: 3,
    type: '漆木竹器',
    dynasty: 'song',
    dynastyName: '宋代',
    desc: '云纹剔犀，黑红交替',
    history: '宋代剔犀漆碗，在胎上交替髹涂黑红漆数十层，再以刀雕刻云纹，断面可见层叠漆色。剔犀又称"云雕"，是中国漆器传统工艺，传世品稀少。',
    weight: { small: 1, medium: 5, large: 11 }
  },
  {
    id: 'g-qiangjinpan',
    name: '戗金漆盘',
    icon: '🍽️',
    imageUrl: 'mini-assets/gifts/icons/g-qiangjinpan.png',
    photoUrl: 'mini-assets/gifts/photos/g-qiangjinpan.jpg',
    rarity: 2,
    type: '漆木竹器',
    dynasty: 'ming',
    dynastyName: '明代',
    desc: '永乐戗金填彩漆器',
    history: '明代永乐时期戗金漆盘，在漆面刻纹后填金粉。戗金漆器始于战国，盛于宋明。永乐漆器工艺精湛，为宫廷御用。',
    weight: { small: 6, medium: 17, large: 8 }
  },
  {
    id: 'g-zhukebitong',
    name: '竹刻笔筒',
    icon: '🎋',
    imageUrl: 'mini-assets/gifts/icons/g-zhukebitong.png',
    photoUrl: 'mini-assets/gifts/photos/g-zhukebitong.jpg',
    rarity: 2,
    type: '漆木竹器',
    dynasty: 'qing',
    dynastyName: '清代',
    desc: '竹刻留青山水笔筒',
    history: '清代竹刻笔筒，以"留青"技法在竹皮上雕刻山水人物。留青竹刻保留竹青为纹，竹肌为地，层次分明。嘉定派竹刻代表为朱氏三代，金陵派以濮仲谦为首。',
    weight: { small: 7, medium: 19, large: 7 }
  },

  // ========== 织绣服饰（10件） ==========
  {
    id: 'g-kesi',
    name: '缂丝牡丹',
    icon: '🧵',
    imageUrl: 'mini-assets/gifts/icons/g-kesi.png',
    photoUrl: 'mini-assets/gifts/photos/g-kesi.jpg',
    rarity: 4,
    type: '织绣服饰',
    dynasty: 'song',
    dynastyName: '宋代',
    desc: '一寸缂丝一寸金',
    history: '宋代缂丝，以"通经断纬"技法织成，正反两面纹饰相同。宋代缂丝以朱克柔、沈子蕃为名家，一幅牡丹图可达数月方成。缂丝是中国丝织工艺的巅峰，有"一寸缂丝一寸金"之誉。',
    weight: { small: 0, medium: 2, large: 8 }
  },
  {
    id: 'g-shujin',
    name: '蜀锦',
    icon: '🧶',
    imageUrl: 'mini-assets/gifts/icons/g-shujin.png',
    photoUrl: 'mini-assets/gifts/photos/g-shujin.jpg',
    rarity: 3,
    type: '织绣服饰',
    dynasty: 'sanguo',
    dynastyName: '蜀汉',
    desc: '成都蜀锦，四大名锦之首',
    history: '四川成都所产蜀锦，已有两千余年历史。三国时期诸葛亮大力发展蜀锦，"决敌之资，唯仰锦耳"。蜀锦以经锦为主，色彩鲜艳，纹饰有方方锦、雨丝锦等。',
    weight: { small: 3, medium: 8, large: 16 }
  },
  {
    id: 'g-songjin',
    name: '宋锦',
    icon: '🧶',
    imageUrl: 'mini-assets/gifts/icons/g-songjin.png',
    photoUrl: 'mini-assets/gifts/photos/g-songjin.jpg',
    rarity: 2,
    type: '织绣服饰',
    dynasty: 'song',
    dynastyName: '宋代',
    desc: '苏州宋锦，织金织银',
    history: '苏州宋锦始于宋代，以织金、织银为特色。宋锦分重锦、细锦、匣锦三类，纹饰有龟背纹、锁子纹、八达晕等。宋锦色泽典雅，经久耐用，为书画装裱常用。',
    weight: { small: 9, medium: 18, large: 6 }
  },
  {
    id: 'g-yunjin',
    name: '云锦',
    icon: '👘',
    imageUrl: 'mini-assets/gifts/icons/g-yunjin.png',
    photoUrl: 'mini-assets/gifts/photos/g-yunjin.jpg',
    rarity: 3,
    type: '织绣服饰',
    dynasty: 'ming',
    dynastyName: '明代',
    desc: '南京云锦，龙袍面料',
    history: '南京云锦始于东晋，盛于明清。以"妆花"工艺著称，大量使用金线、孔雀羽毛。云锦为皇帝龙袍、宫廷服饰专用面料，织造工艺极为复杂，至今无法完全机器替代。',
    weight: { small: 2, medium: 6, large: 14 }
  },
  {
    id: 'g-suxiutuan',
    name: '苏绣团扇',
    icon: '🪭',
    imageUrl: 'mini-assets/gifts/icons/g-suxiutuan.png',
    photoUrl: 'mini-assets/gifts/photos/g-suxiutuan.jpg',
    rarity: 2,
    type: '织绣服饰',
    dynasty: 'qing',
    dynastyName: '清代',
    desc: '双面绣团扇',
    history: '清代苏州双面绣团扇，扇面两面绣相同图案，针脚整齐不见线头。苏绣以"平、齐、细、密、和、光、顺、匀"八字著称，为四大名绣之首。',
    weight: { small: 8, medium: 16, large: 7 }
  },
  {
    id: 'g-sushayi',
    name: '素纱襌衣',
    icon: '👗',
    imageUrl: 'mini-assets/gifts/icons/g-sushayi.png',
    photoUrl: 'mini-assets/gifts/photos/g-sushayi.jpg',
    rarity: 4,
    type: '织绣服饰',
    dynasty: 'xihan',
    dynastyName: '西汉',
    desc: '马王堆出土，仅49克',
    history: '1972年长沙马王堆一号汉墓出土，西汉直裾素纱襌衣，衣长128厘米，重仅49克。薄如蝉翼，折叠后可放入火柴盒。代表了西汉纺织工艺的最高水平，现代技术难以完全复制。',
    weight: { small: 0, medium: 1, large: 6 }
  },
  {
    id: 'g-tangruqun',
    name: '唐代襦裙',
    icon: '👗',
    imageUrl: 'mini-assets/gifts/icons/g-tangruqun.png',
    photoUrl: 'mini-assets/gifts/photos/g-tangruqun.jpg',
    rarity: 3,
    type: '织绣服饰',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '唐代仕女常服',
    history: '唐代仕女常服，上着短襦下着长裙，裙腰高系至胸上。唐代服饰开放华丽，色彩鲜艳。新疆吐鲁番阿斯塔那墓出土的绢画和陶俑生动再现了唐代女性的服饰风貌。',
    weight: { small: 1, medium: 5, large: 12 }
  },
  {
    id: 'g-mingbuzi',
    name: '明代补子',
    icon: '🏅',
    imageUrl: 'mini-assets/gifts/icons/g-mingbuzi.png',
    photoUrl: 'mini-assets/gifts/photos/g-mingbuzi.jpg',
    rarity: 2,
    type: '织绣服饰',
    dynasty: 'ming',
    dynastyName: '明代',
    desc: '官服胸背补子',
    history: '明代官员常服胸背所缀补子，文官绣禽鸟，武官绣走兽。品级不同纹饰不同：一品仙鹤，二品锦鸡，三品孔雀等。补子制度始于明初，延续至清末，是中国服饰等级制度的典型体现。',
    weight: { small: 6, medium: 14, large: 5 }
  },
  {
    id: 'g-qinglongpao',
    name: '清代龙袍',
    icon: '👘',
    imageUrl: 'mini-assets/gifts/icons/g-qinglongpao.png',
    photoUrl: 'mini-assets/gifts/photos/g-qinglongpao.jpg',
    rarity: 4,
    type: '织绣服饰',
    dynasty: 'qing',
    dynastyName: '清代',
    desc: '乾隆明黄缎绣龙袍',
    history: '清代乾隆皇帝龙袍，明黄色缎面，绣九条金龙，前胸后背各一，两肩各一，膝下各二，里襟一。龙袍以缂丝或刺绣制成，工艺精湛。乾隆龙袍现藏北京故宫，代表了清代宫廷服饰的最高水平。',
    weight: { small: 0, medium: 2, large: 7 }
  },
  {
    id: 'g-cixiuxiangnang',
    name: '刺绣香囊',
    icon: '👜',
    imageUrl: 'mini-assets/gifts/icons/g-cixiuxiangnang.png',
    photoUrl: 'mini-assets/gifts/photos/g-cixiuxiangnang.jpg',
    rarity: 1,
    type: '织绣服饰',
    dynasty: 'qing',
    dynastyName: '清代',
    desc: '苏绣香囊，随身佩饰',
    history: '清代苏绣香囊，以丝绸为面，内填香料。香囊又称"荷包"，是清代女性随身佩饰，也是定情信物。绣工精美，图案有花卉、瓜果、吉祥纹样等。',
    weight: { small: 27, medium: 10, large: 4 }
  },

  // ========== 杂项珍玩（10件） ==========
  {
    id: 'g-coin',
    name: '开元通宝',
    icon: '🪙',
    imageUrl: 'mini-assets/gifts/icons/g-coin.png',
    photoUrl: 'mini-assets/gifts/photos/g-coin.jpg',
    rarity: 1,
    type: '杂项珍玩',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '唐初铸币，字迹遒劲',
    history: '唐武德四年(621年)废五铢钱铸"开元通宝"，由欧阳询书写钱文。"开元"非年号，意为开创新纪元。此钱确立了"通宝"钱制，沿用一千三百余年，是中国货币史上的重要里程碑。',
    weight: { small: 30, medium: 8, large: 2 }
  },
  {
    id: 'g-seal',
    name: '传国玉玺',
    icon: '🔖',
    imageUrl: 'mini-assets/gifts/icons/g-seal.png',
    photoUrl: 'mini-assets/gifts/photos/g-seal.jpg',
    rarity: 4,
    type: '杂项珍玩',
    dynasty: 'qin',
    dynastyName: '秦代',
    desc: '和氏璧所刻，受命于天',
    history: '传秦始皇以和氏璧镌刻传国玉玺，丞相李斯书"受命于天，既寿永昌"八字鸟篆。此玺为历代皇帝正统象征，历经战乱遗失。唐末失踪，成为千古之谜。后世所见的"传国玺"多为仿制。',
    weight: { small: 0, medium: 1, large: 5 }
  },
  {
    id: 'g-tongjinghaishou',
    name: '海兽葡萄镜',
    icon: '🪞',
    imageUrl: 'mini-assets/gifts/icons/g-tongjinghaishou.png',
    photoUrl: 'mini-assets/gifts/photos/g-tongjinghaishou.jpg',
    rarity: 2,
    type: '杂项珍玩',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '唐代海兽葡萄镜',
    history: '唐代铜镜精品，背面铸海兽葡萄纹。高浮雕工艺，纹饰繁密生动。海兽葡萄纹融合了西域和中国本土文化元素，反映了唐代丝绸之路文化交流的盛况。',
    weight: { small: 5, medium: 20, large: 8 }
  },
  {
    id: 'g-guqin',
    name: '古琴',
    icon: '🎸',
    imageUrl: 'mini-assets/gifts/icons/g-guqin.png',
    photoUrl: 'mini-assets/gifts/photos/g-guqin.jpg',
    rarity: 4,
    type: '杂项珍玩',
    dynasty: 'song',
    dynastyName: '宋代',
    desc: '宋代官琴，焦尾遗韵',
    history: '宋代官府所制古琴，七弦十三徽。古琴有三千余年历史，为"琴棋书画"四艺之首。宋代官琴以"宣和殿"制为上品，音色清越。传世宋琴稀少，每张均为无价之宝。',
    weight: { small: 0, medium: 2, large: 6 }
  },
  {
    id: 'g-weiqizi',
    name: '围棋子',
    icon: '⚫',
    imageUrl: 'mini-assets/gifts/icons/g-weiqizi.png',
    photoUrl: 'mini-assets/gifts/photos/g-weiqizi.jpg',
    rarity: 2,
    type: '杂项珍玩',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '唐代围棋子，琉璃质',
    history: '唐代琉璃质围棋子，黑白各半。唐代围棋盛行，遣唐使将围棋传入日本。新疆吐鲁番阿斯塔那唐墓出土有木质围棋盘和围棋子，为现存最早的围棋实物之一。',
    weight: { small: 10, medium: 17, large: 6 }
  },
  {
    id: 'g-touzi',
    name: '骰子',
    icon: '🎲',
    imageUrl: 'mini-assets/gifts/icons/g-touzi.png',
    photoUrl: 'mini-assets/gifts/photos/g-touzi.jpg',
    rarity: 1,
    type: '杂项珍玩',
    dynasty: 'tang',
    dynastyName: '唐代',
    desc: '唐代骨制骰子',
    history: '唐代骨制骰子，六面刻点。骰子历史悠久，唐代已流行于各种博弈游戏。唐传奇《李娃传》中有掷骰场景。骰子也是现代麻将、色子等游戏的始祖。',
    weight: { small: 23, medium: 13, large: 3 }
  },
  {
    id: 'g-xianglu',
    name: '宣德炉',
    icon: '🪔',
    imageUrl: 'mini-assets/gifts/icons/g-xianglu.png',
    photoUrl: 'mini-assets/gifts/photos/g-xianglu.jpg',
    rarity: 2,
    type: '杂项珍玩',
    dynasty: 'ming',
    dynastyName: '明代',
    desc: '宣德炉，铜质精炼',
    history: '明宣德三年(1428年)铸造，以暹罗国进贡的风磨铜为材，加入金、银等三十余种金属。色泽温润，有猪肝色、蟹壳青、藏经纸色等。宣德炉为铜炉之冠，后世仿制不断。',
    weight: { small: 7, medium: 19, large: 8 }
  },
  {
    id: 'g-huluqiqi',
    name: '葫芦器',
    icon: '🎃',
    imageUrl: 'mini-assets/gifts/icons/g-huluqiqi.png',
    photoUrl: 'mini-assets/gifts/photos/g-huluqiqi.jpg',
    rarity: 1,
    type: '杂项珍玩',
    dynasty: 'qing',
    dynastyName: '清代',
    desc: '范制葫芦，文玩清供',
    history: '清代范制葫芦器，将幼葫芦纳入模具生长成型，表面有阳文花纹。康熙时期宫中设有葫芦园专门种植。葫芦器为文人案头清供，也可作蝈蝈笼。',
    weight: { small: 17, medium: 15, large: 5 }
  },
  {
    id: 'g-biyanhu',
    name: '鼻烟壶',
    icon: '💧',
    imageUrl: 'mini-assets/gifts/icons/g-biyanhu.png',
    photoUrl: 'mini-assets/gifts/photos/g-biyanhu.jpg',
    rarity: 2,
    type: '杂项珍玩',
    dynasty: 'qing',
    dynastyName: '清代',
    desc: '内画鼻烟壶，玻璃胎',
    history: '清代内画鼻烟壶，以弯曲细笔从壶口伸入反向作画。鼻烟壶始于明末清初，材质有玻璃、水晶、玛瑙等。内画鼻烟壶为中国独有工艺，京派、冀派名家辈出。',
    weight: { small: 8, medium: 16, large: 7 }
  },
  {
    id: 'g-chaozhu',
    name: '朝珠',
    icon: '📿',
    imageUrl: 'mini-assets/gifts/icons/g-chaozhu.png',
    photoUrl: 'mini-assets/gifts/photos/g-chaozhu.jpg',
    rarity: 3,
    type: '杂项珍玩',
    dynasty: 'qing',
    dynastyName: '清代',
    desc: '翡翠朝珠，108颗',
    history: '清代官员朝服所佩朝珠，共108颗，以翡翠、珊瑚、琥珀等制成。朝珠制度始于清初，源于佛教念珠。四颗大珠将108颗分为四份，象征四季。',
    weight: { small: 2, medium: 7, large: 15 }
  }
];

module.exports = { GIFT_POOL };
